### ISSUE TITLE
Try Running IronPdf in a Separate Docker Container from your Main Application

### ISSUE THREAD

**Issue by djrecipe** [SypleMatt/ironpdf-segfault#1]
Now Iron Software offers a prepackaged Docker container which allows you to run IronPdf in an isolated container.

https://ironpdf.com/how-to/ironpdfengine-docker/

This is one option for avoiding this seg fault issue.

**Comment by michael-ironsoftware** [comment]
@SypleMatt This issue is now fixed in `IronPdf.Linux` **`2023.5.9`**. Please update your dependencies.

```xml
<ItemGroup>
  <PackageReference Include="IronPdf.Linux" Version="2023.5.9" />
  <PackageReference Include="IronPdf.Native.Chrome.Linux" Version="2023.5.14327" />
  <PackageReference Include="IronPdf.Slim" Version="2023.5.9" />
</ItemGroup>
```

![image](https://user-images.githubusercontent.com/97211369/236792395-e90116e0-7fd5-4883-bddf-53dad03fb49c.png)
